default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: 268435456
    namespace: development

development:
  <<: *default

test:
  store_options:
    max_size: 268435456
    namespace: test

production:
  database: cache
  store_options:
    max_size: 268435456
    namespace: production
